import { useState } from "react"
import Head from "next/head"
import { useSession } from "next-auth/react"
import { api, type RouterOutputs } from "../utils/api"
import { Header } from "../components/Header"

export default function Home() {
  return (
    <>
      <Head>
        <title>Notetaker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Content />
      </main>
    </>
  )
}

type Topic = RouterOutputs["topic"]["getAll"][0]

const Content: React.FC = () => {
  const { data: sessionData } = useSession()

  const [selectedTopic, setSelectedTopic] = useState<Topic | null>(null)

  const { data: topics, refetch: refetchTopics } = api.topic.getAll.useQuery(
    undefined,
    {
      enabled: sessionData?.user !== undefined,
      onSuccess: (data) => {
        setSelectedTopic(selectedTopic ?? data[0] ?? null)
      },
    }
  )

  const createTopic = api.topic.create.useMutation({
    onSuccess: () => {
      void refetchTopics()
    },
  })

  return (
    <div className="mx-auto mt-5 grid max-w-7xl grid-cols-4 gap-2">
      <div className="px-2">
        <div className="flex flex-col gap-4 divide-y-2 divide-gray-100">
          <ul className="bg-neutral-100 p-2">
            {topics?.map((topic) => (
              <li key={topic.id}>
                <a
                  href="#"
                  onClick={(e) => {
                    e.preventDefault()
                    setSelectedTopic(topic)
                  }}
                >
                  {topic.title}
                </a>
              </li>
            ))}
          </ul>
          <input
            type="text"
            placeholder="New topic"
            className="w-full rounded-md border-2 border-gray-200 px-4 py-2"
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                createTopic.mutate({
                  title: e.currentTarget.value,
                })
                e.currentTarget.value = ""
              }
            }}
          />
        </div>
      </div>
      <div className="col-span-3"></div>
    </div>
  )
}
